-- La bannière promo n'est plus limitée à une seule ligne : l'admin peut désormais en ajouter,
-- modifier ou supprimer plusieurs, chacune avec sa propre visibilité et son ordre d'affichage
-- (l'app affiche toutes les bannières visibles, plus une seule image fixe).
ALTER TABLE banner DROP CONSTRAINT banner_id_check;
ALTER TABLE banner ALTER COLUMN id DROP DEFAULT;
ALTER TABLE banner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('banner', 'id'), (SELECT COALESCE(MAX(id), 0) FROM banner) + 1, false);

ALTER TABLE banner ADD COLUMN display_order INT NOT NULL DEFAULT 0;

CREATE INDEX idx_banner_visible_display_order ON banner (visible, display_order);
